CREATE TABLE Monitor(
CodMonitor INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
NombreMonitor VARCHAR(40) NOT NULL);

CREATE TABLE Estudiante(
CodEstudiante INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
CodCarne VARCHAR(13) NOT NULL,
NombreEstudiante VARCHAR(40) NOT NULL,
PlanAcademico VARCHAR(40));

CREATE TABLE Equipo(
CodEquipo INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
CodBarras SMALLINT NOT NULL,
NombreEquipo VARCHAR(40),
Descripcion VARCHAR(250));

CREATE TABLE Estudiante_Equipo(
CodEstudianteEquipo INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
CodEstudiante INTEGER NOT NULL,
CodEquipo INTEGER NOT NULL,
FOREIGN KEY (CodEstudiante) REFERENCES Estudiante(CodEstudiante),
FOREIGN KEY (CodEquipo) REFERENCES Equipo(CodEquipo));

CREATE TABLE Prestamo(
CodPrestamo INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
CodMonitor INTEGER NOT NULL,
CodPrestamo INTEGER NOT NULL,
Entregado BOOLEAN NOT NULL,
FechaHora TIMESTAMP NOT NULL,
FOREIGN KEY (CodMonitor) REFERENCES Monitor(CodMonitor),
FOREIGN KEY (CodEstudianteEquipo) REFERENCES Estudiante_Equipo(CodEstudianteEquipo))


